general {
	hide_cursor = true;
}

background {
	path = screenshot
	blur_passes = 1
}

input-field {
	size = 20%, 5%
	outline_thickness = 3
	inner_color = rgba(0, 0, 0, 0.25)
	outer_color = rgba(984ac1ee) rgba(0094ffee)
    font_color = rgb(200, 200, 200)
	fade_on_empty = false
}
